export const Values = {
  SignUpLink: "Don't have a account?",
  SignInLink: "have an account?",
  SignUp: "Sign Up",
  SignIn: "Sign In",
  UserId: "User ID",
  EmailPredefinedOption:
    "Click the checkbox to use email us predefined sign in option",
  PholePredefinedOption:
    "Click the checkbox to use phone us predefined sign in option",
  PhoneNumber: "Phone",
  CountryCode: "Country Code",
  Email: "Email",
  Password: "Password",
  ConfirmPassword: "Confirm Password",
  CreateAccount: "Create account",
  UserName: "Username",
  FirstName: "Firstname",
  LastName: "Lastname",
  Title: "Title",
  Suffix: "Suffix",
  PasswordPlaceholder: "Password(8-24 char)",
  RepeatPassowrdPlaceholder: "Repeat Password",
  GoogleLogin: "Sign Up with Google",
  FaceBookLogin: "Sign Up with Facebook",
  GitHubLogin: "Sign Up with Github",
  ForgotPassword: "Forgot password?",
  RememberMe: "Remember me",

  //Tooltip content
  EmailTooltip: "Make sure your email is valid.",
  MobileTooltip: "MX phone number must be 10 digits.",
  MobileValidationError: "phone number must be 10 digits",
  Required: "Field is required",
  FirstNameError: "Firstname is required",
  LastNameError:  "Lastname is required",
  EmailError: "Email is required",
  UserNameError: "Username is required",
  UserNameMaxError: "Minimum 6 characters is required",
  PasswordError: "Password is required",
  ConformPasswordError: "Confirm password is required",
  IsPasswordMatch: "Password must match",
  CountryCodeError: "Select country code",
  PhoneError: "Number is required",
  //Name
  NameCountryCode: "CountryCode",
  NamePhoneNumber: "PhoneNumber",
  NamePassword: "Password",
  NameConfirmPassword: "ConfirmPassword"
};
